services:
  auctionsystem:
    container_name: AuctionSystem
    image: auctionsystem
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8080:80"
